parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 8889
    database_name: elearning_smeagonline
    database_user: root
    database_password: 'root'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: iwee5o0ygqgwsg4og0w44ocksk800c8
    webpack_base_url: http://elearning.smeagonline.local
    user_partner: none