parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: 8889
    database_name: edusoho
    database_user: root
    database_password: 'root'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: zh_CN
    secret: grnog1jmi884sgw80wsog0gsswoc4cs
    webpack_base_url: http://smeagonline.local
    user_partner: none