api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   /api

tbazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

topxia_mobile_v2:
    resource: "@TopxiaMobileBundleV2/Resources/config/routing.yml"
    prefix:   /mapi_v2

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

app_admin:
    resource: "@AppBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

_plugins:
   resource: routing_plugins.yml

# Internal routing configuration to handle ESI
# _internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal